import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";
import { readUserSession } from "@/lib/actions";
import { Button } from "@/components/ui/button";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nascoo",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data } = await readUserSession();
  const logout = async () => {
    "use server";
    const supabase = await createSupabaseServerClient();
    await supabase.auth.signOut();
    redirect("/oauth");
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        {data.session ? (
          <div className="flex flex-col">
            <Link href="/">
              <Button>Home</Button>
            </Link>
            <Link href="/todo">
              <Button>Todo List</Button>
            </Link>
            <form action={logout}>
              <Button>SignOut</Button>
            </form>
          </div>
        ) : (
          <div className="flex flex-col">
            {/* <Link href="/auth-server">Auth Server</Link>
            <Link href="/auth-client">Auth Client</Link>
            <Link href="/oauth">oAuth</Link> */}
          </div>
        )}
        {children} <Toaster />
      </body>
    </html>
  );
}
